config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homePage'
  get '/home' => 'pages#home'
  get '/who' => 'pages#who'
  get '/mentions' => 'pages#mentions'
  get '/conditions' => 'pages#conditions'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  
  resources :carts
  resources :cart_products
  
  resources :orders do 
    resources :payments, only: :new
  end
  resources :order_products

  resources :products do 
    resources :tags
  end

  resources :favorite_profils

  get "search", to: "products#search"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-grey">
    <div class="container">
        <div class="grey-box">
            <div class="box-pay font-42">
                <div class="row d-flex justify-content-around">
                    <div class="col-3 col-sm-3 col-md-3 col-lg-3 p-0">
                        <i class="gold d-flex justify-content-center mb-3 font-80 fas fa-palette"></i>
                        <h5 class="text-center font-footer">Selection d'artistes</h5>
                    </div>
                    <div class="col-3 col-sm-3 col-md-3 col-lg-3 p-0">
                        <i class="gold d-flex justify-content-center mb-3 font-80 fas fa-truck"></i>
                        <h5 class="text-center font-footer">Livraison internationale</h5>
                    </div>
                    <div class="col-3 col-sm-3 col-md-3 col-lg-3 p-0">
                        <i class="gold d-flex justify-content-center mb-3 font-80 fas fa-box"></i>
                        <h5 class="text-center font-footer">Retour gratuits</h5>
                    </div>
                    <div class="col-3 col-sm-3 col-md-3 col-lg-3 p-0">
                        <i class="gold d-flex justify-content-center mb-3 font-80 fas fa-lock"></i>
                        <h5 class="text-center font-footer">Paiements sécurisés</h5>
                    </div>
                </div>
            </div>
            <div class="box-pay font-42">
                <div class="row d-flex justify-content-around">
                    <div class="cb col-sm-2 col-md-2 col-lg-2"><i class="fab fa-cc-visa"></i></div>
                    <div class="cb col-sm-2 col-md-2 col-lg-2"><i class="fab fa-cc-mastercard"></i></div>
                    <div class="cb col-sm-2 col-md-2 col-lg-2"><i class="fab fa-cc-amex"></i></div>
                    <div class="cb col-sm-2 col-md-2 col-lg-2"><i class="fab fa-cc-stripe"></i></div>
                    <div class="cb col-sm-2 col-md-2 col-lg-2"><i class="fab fa-cc-paypal"></i></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer pb-5 pt-3">
    <div class="container">
        <div class="row">
            <div class="section-white">
                <div class="d-flex pl-4 pr-4">
                    <% image_tag("logo.png", class:"logo-css logo-css-footer") %>
                    
                    <div class="info-footer mb-2">
                        <div class="rubrique">
                            <div class="d-flex justify-content-center col-md-6 col-xs-12 col-sm-6 ">
                                <div>
                                    <h4>Service Client</h4>
                                    <div class="d-flex flex-column">
                                        <%= link_to 'Mentions légales', mentions_path, class:"link-footer para-contact font-14 m-0" %>
                                        <%= link_to 'Conditions générales de vente', conditions_path, class:"link-footer para-contact font-14 m-0" %>
                                    </div>
                                </div>
                            </div>

                            <div class="d-flex justify-content-center col-md-6 col-xs-12 col-sm-6">
                                <div>
                                    <h4>Qui sommes-nous ?</h4>
                                    <%= link_to 'À propos de nous', who_path, class:"link-footer para-contact font-14 m-0" %>
                                    <%# <p class="mb-1"><a href="" class="link-footer font-14 m-0">Contact</a></p>
                                    <p class="mb-1"><a href="" class="link-footer font-14 m-0">FAQ</a></p> %>
                                    
                                </div>
                            </div>
                        </div>

                        <%# <div class="follow mt-4">
                            <p class="m-0 font-14">Suivez-nous</p>
                            <a href="" class="link-footer"><i class="fab fa-facebook-f"></i></a>
                            <a href="" class="link-footer"><i class="fab fa-instagram"></i></a>
                            <a href="" class="link-footer"><i class="fab fa-pinterest-p"></i></a>
                        </div> %>
                    </div>
                    
                </div>
            </div>

            <div class="flex-footer">
                <div class="flex-footer-star">
                    <p class="text-center mx-1 font-12">Le Vide Grenier a reçu la note de 9.8/10 sur 1810 avis.</p>
                    <div class="d-flex justify-content-center">
                        <i class="gold fas fa-star"></i>
                        <i class="gold fas fa-star"></i>
                        <i class="gold fas fa-star"></i>
                        <i class="gold fas fa-star"></i>
                        <i class="gold fas fa-star"></i>
                    </div>
                </div>
                <p class="text-center mx-1 font-12">© 2020 Le Vide Grenier</p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to root_path do %>
    <%= image_tag("logo.png", class:"logo-css-nav") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse navbar-flex mr-5" id="navbarSupportedContent">

    <%= link_to home_path, class:'nav-link p-0 m-O margin-nav cart-logo' do %>
      <i class="fas fa-paint-brush"></i>
    <% end %>
    
    <form class="form-inline my-2 my-lg-0 search-form none" action="/search">
      <input class="form-search form-control mr-sm-2" id="input_search" name="q" type="search" placeholder="Tapez ici votre recherche" aria-label="Search">
    </form>

    <button class="cart-logo nav-link button-search-logo margin-nav p-0" id="button-search-logo"><i class="fas fa-search"></i></button>

    <ul class="navbar-nav drop-menu">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle margin-nav p-0 m-O cart-logo" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="cart-logo far fa-user"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <%= link_to 'Mes produits', products_path, class:'dropdown-item' %>
            <% end %>
            <%= link_to 'Mes commandes', orders_path, class:'dropdown-item' %>
            <%# link_to 'Mes favoris', products_path, class:'dropdown-item' %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
          <% else %>
            <%= link_to "Se connecter", new_user_session_path, class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Créer un compte", new_user_registration_path, class:"dropdown-item"%>
          <% end %>
        </div>
      </li>
    </ul>

    <%= link_to cart_path(@cart), class:'nav-link p-0 m-O margin-nav cart-logo' do %>
      <% sum = 0 %>
      <i class="fas fa-shopping-cart"><span class="number-product"><% @cart.cart_products.each{ |x| sum += x.quantity } %><%= sum %></span></i>      
    <% end %>
    
  </div>
</nav>