config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homePage'
  get '/home' => 'pages#home'
  get '/who' => 'pages#who'
  get '/mentions' => 'pages#mentions'
  get '/conditions' => 'pages#conditions'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  
  resources :carts
  resources :cart_products
  
  resources :orders do 
    resources :payments, only: :new
  end
  resources :order_products

  resources :products do 
    resources :tags
  end

  resources :favorite_profils

  get "search", to: "products#search"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user
  has_many :products, through: :order_product
  has_many :order_products, dependent: :destroy
  monetize :amount_cents

  def add_item(product)
    current_product = order_products.find_by(product_id: product.id)
    unless current_product
      current_product = order_products.build(product_id: product.id)
    end
    current_product
  end

  def stripe_amount(order)
    sum = 0
    order.order_products.each do |order_product|
      sum += order_product.product.price
    end
    sum
  end
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  require 'stripe'
  
  def show
    @order = current_user.orders.find(params[:id])
    authorize @order
  end

  def index
    @orders = policy_scope(Order)
    @order_products = policy_scope(OrderProduct)
  end

  def new
    authorize @order
  end

  def create
    
      @cart.user_id = current_user.id
      current_user.cart = @cart
    
    
    user_cart = current_user.cart.id
    
    if @cart.cart_products.count > 0
      @order = Order.create(cart_id: user_cart, user_id: current_user.id, state: "En attente")
    end
    
    current_user.cart.cart_products.each do |cart_product|
      @order_product = OrderProduct.create(product_id: cart_product.product_id, order_id: @order.id)
    end
    
    @order.amount = @order.stripe_amount(@order)
    @order.save
    array_name_product = []
    @order.order_products.each do |order_product|
      array_name_product << order_product.product.name 
    end
    
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: 'Total',
        amount: @order.amount_cents,
        currency: 'eur',
        quantity: 1
        }],
        success_url: order_url(@order),
        cancel_url: cart_url(@cart)
      )
      
      @order.update(checkout_session_id: session.id)
      
      redirect_to new_order_payment_path(@order)
      
      # current_user.cart.destroy
      authorize @order
    end
    
    def edit
      authorize @order
      # @order = Order.find(params[:id])
      # id = @order.cart_id
      # cart = Cart.all.find_by(id: id)
      # if @order.state == "Payée"
      #   cart.destroy
      # end
    end
    
    def update
    authorize @order
    # @order = Order.find(params[:id])
    # id = @order.cart_id
    # cart = Cart.all.find_by(id: id)
    # if @order.state == "Payée"
    #   cart.destroy
    # end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
    authorize @order
  end

  # def order_params
  #   params.require(:order).permit(:order_product_id)
  # end
end

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="background-cart">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="flex-section section">
                    <h2 class="header-cart"> Mes commandes</h2>
                    <%=link_to home_path, class:"button-return-shop" do %>
                        <p class="mb-0 para-contact">Retour au shopping <i class="fas fa-arrow-right ml-2"></i></p>
                    <% end %> 
                </div>
            </div>
        </div>

        <% unless current_user.orders.count == 0 %>
            <div class="row">
                <div class="col-lg-12 col-12 mx-auto">
                    <% current_user.orders.each do |order| %>
                        <div class="card-product-cart d-flex mb-5 mt-5 mx-auto">
                            <div class="info-in-my-order">
                                <div class="d-flex-info-banner-order section p-0">
                                    <p class="para-contact">Commande effectué le <%= order.created_at.strftime("%d %B %Y")%> <span class="badge badge-primary para-contact ml-3"><%= order.state %></span></p>
                                    <div class="d-flex-columnn">
                                        <p class="mb-1 hide">Total</p>
                                        <p class="gold mb-1"><%= order.amount %> €</p>
                                    </div>
                                    <div class="flex-order">
                                        <%= link_to 'Détails', order_path(order) , class:"para-contact button-order-suivis mb-3"%>
                                        <%= link_to order_path(order), class:"", method: :delete, data: {confirm: "Êtes-vous sûre de vouloir supprimer cette commande ?"}  do %>
                                            <p><i class="gold icone-cart far fa-trash-alt"></i></p>
                                        <% end %>
                                    </div>
                                </div>

                                <% order.order_products.each do |order_product| %>
                                    <div class="card-product-order d-flex">
                                        <% if order_product.product.photo.attachment.nil? %>
                                            <img src="https://media.artsper.com/artwork/227887_1_grid@2x.jpg?MjIyOTI2NDkxNjAxMTE5MDEx" alt="" class="image-cart">
                                        <% else%>
                                            <%= cl_image_tag order_product.product.photo.key, class: "image-order", crop: :fill %>
                                        <% end %>
                                        <div class="info-in-my-order-info">
                                            <%# <div class="info-product-in-cart">
                                            </div> %>
                                                <h5 class="title-product-cart"><%= order_product.product.name.capitalize %></h5>
                                                <p class="cart-price-product-order"><%= humanized_money(order_product.product.price) %> €</p>
                                            <%# <div class="ml-2 div-price-cart">
                                            </div> %>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        <% else %>
            <div class="row">
                <div class="col-12 mx-auto">
                    <div class="card-no-product text-center">
                        <div class="border-circle-info">
                            <p class="info-font">i</p>
                        </div>
                        <p class="m-0 para-contact font-info-text">Vous n'avez passé aucune commande à ce jour</p>
                    </div>
                </div>
            </div>
        <% end %>


    </div>
</div>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<div class="background-cart">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="flex-section section">
                    <h2 class="header-cart"> Récapitulatif de la commande</h2>
                    <%=link_to orders_path, class:"button-return-shop mr-3" do %>
                        <p class="mb-0 para-contact">Retour aux commandes <i class="fas fa-arrow-right ml-2"></i></p>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-10 col-12 mx-auto">
                <div class="card-product-cart d-flex mb-5 mt-5 mx-auto">
                    <div class="info-in-my-order">

                        <div class="d-flex-info-banner-order section p-0">
                            <p class="para-contact">Commande effectué le <%= @order.created_at.strftime("%d %B %Y")%> <span class="badge badge-primary para-contact ml-3"><%= @order.state %></span></p>
                            <div class="d-flex-columnn">
                                <p class="mb-1 hide">Total</p>
                                <p class="gold mb-1"><%= @order.amount %> €</p>
                            </div>
                        </div>

                        <% @order.order_products.each do |order_product| %>
                            <div class="card-product-order d-flex">
                                <% if order_product.product.photo.attachment.nil? %>
                                    <img src="https://media.artsper.com/artwork/227887_1_grid@2x.jpg?MjIyOTI2NDkxNjAxMTE5MDEx" alt="" class="image-cart">
                                <% else%>
                                    <%= cl_image_tag order_product.product.photo.key, class: "image-order", crop: :fill %>
                                <% end %>
                                <div class="info-in-my-order-info">
                                    <%#  <div class="info-product-in-cart">
                                    </div> %>
                                        <h5 class="title-product-cart"><%= order_product.product.name %></h5>
                                        <p class="cart-price-product-order"><%= humanized_money(order_product.product.price) %> €</p>
                                    <%# <div class="ml-2 div-price-cart">
                                    </div> %>
                                </div>
                            </div>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>