config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homePage'
  get '/home' => 'pages#home'
  get '/who' => 'pages#who'
  get '/mentions' => 'pages#mentions'
  get '/conditions' => 'pages#conditions'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  
  resources :carts
  resources :cart_products
  
  resources :orders do 
    resources :payments, only: :new
  end
  resources :order_products

  resources :products do 
    resources :tags
  end

  resources :favorite_profils

  get "search", to: "products#search"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  # has_many :cart_products, dependent: :nullify
  has_many :cart_products, dependent: :destroy

  def add_product(product)
    current_product = cart_products.find_by(product_id: product.id)
    unless current_product
      current_product = cart_products.build(product_id: product.id)
      current_product.increment(:quantity)
    end
    current_product
  end

  def total_price
    cart_products.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!


  def show
    @order = Order.new
    authorize @cart
  end

  def index
  end

  def new
    @cart = Cart.new(cart_params)
    authorize @cart
  end

  def create
    @cart = Cart.create(user_id: current_user.id)
    authorize @cart
  end

  def edit
    authorize @cart
  end

  def update
    authorize @cart
  end

  def destroy
    @cart.destroy #if @cart.id === session[:cart_id]
    #session[:cart_id] = nil
    redirect_to root_path
    authorize @cart
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.require(:cart).permit(:product, :price, :products_counter, :user_id)
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end

end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<div class="background-cart">
    <div class="container ">
        <div class="row">
            <div class="col-12">
                <div class="flex-section section">
                    <div class="header-cart d-flex">
                        <h2 class="">Panier</h2>
                        <h2 class="count-of-product d-flex justify-content-center align-items-center"><%= @cart.cart_products.count %></h2>
                    </div>
                    <%=link_to home_path, class:"button-return-shop button-return-shopp" do %>
                        <p class="para-contact mb-0 mr-3">Continuer le shopping <i class="fas fa-arrow-right ml-2"></i></p>
                    <% end %>
                </div>
            </div>
        </div>

        <% unless @cart.cart_products.count == 0 %>
            <div class="row flex-cart mt-5">
                <%# <div class="mt-5 "> %>
                    <div class="col-xl-8 col-lg-12 p-0">
                        <div class="mb-5 mr-2">
                            <% @cart.cart_products.each do |cart_product| %>
                                <div class="card-product-cart d-flex">
                                    <% if cart_product.product.photo.attachment.nil? %>
                                        <img src="https://media.artsper.com/artwork/227887_1_grid@2x.jpg?MjIyOTI2NDkxNjAxMTE5MDEx" alt="" class="image-cart">
                                    <% else%>
                                        <%= cl_image_tag cart_product.product.photo.key, class: "image-cart", crop: :fill %>
                                    <% end %>
                                    <div class="info-in-my-cart">
                                        
                                            <div class="info-product-in-cart">
                                                <h5 class="title-product-cart"><%= link_to cart_product.product.name.capitalize, product_path(cart_product.product), class:"lt-product" %></h5>
                                                <p class="artist-name-cart para-contact"><%= cart_product.product.category.capitalize %></p>
                                            </div>
                                            <p class="div-price-cart cart-price-product m-0"><%= humanized_money(cart_product.product.price) %> €</p>
                                            <%# <div class="ml-2 div-price-cart">
                                                <p class="font-12 prix-titre">PRIX</p>
                                            </div> %>
                                            <div>
                                                <%= link_to cart_product_path(cart_product), method: :delete, data: {confirm: "Êtes-vous sûre de vouloir supprimer cet article ?"}  do %>
                                                    <i class="gold icone-cart far fa-trash-alt d-flex justify-content-center mb-3 poubelle"></i>
                                                <% end %>
                                                <button class="button-heart-cart d-flex justify-content-center coeur"><i id="" class="far fa-heart button-like-cart gold "></i></button>
                                            </div>
                                        
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <%# </div>

                <div class="row"> %>
                    <div class="col-xl-4 col-lg-12  col-xs-12 test-00 p-0">
                        <div class="panier-total mb-1">
                            <div class="d-flex justify-content-between align-items-end pb-3">
                                <h5 class="m-0 p-0">TOTAL</h5>
                                <%= link_to cart_path(@cart), method: :delete, class:"", id:"del-button-hid", data: {confirm: "Êtes-vous sûre de vouloir supprimer ce panier ?"} do %>
                                    <i class="gold icone-cart far fa-trash-alt"></i>
                                <% end %>
                            </div>
                            <p class="gold price-total-cart"><%= humanized_money(@cart.total_price) %> €</p>
                            <div class="cart-livraison d-flex">
                                <p class="button-like-cart mr-3"> <i class="fas fa-truck"></i></p>
                                <p class="para-contact">Livraison sous 7 jours en moyenne</p>
                            </div>
                            <%= simple_form_for @order do |f| %>
                                <%= f.button :submit, "Valider mon panier", class:" para-contact button-cart mb-3", id:"btn-pay" %>
                            <% end %>
                            <img src="https://d17h7hjnfv5s46.cloudfront.net/assets/build/images/elements/cards_all.fbf13bc8.png" alt="" class="img-cart-paiement">
                        </div>
                    </div>
                <%# </div> %>
            </div>
        <% else %>
            <div class="row">
                <div class="col-12 mx-auto">
                    <div class="card-no-product text-center">
                        <div class="border-circle-info">
                            <p class="info-font">i</p>
                        </div>
                        <p class="m-0 para-contact font-info-text">Il n'y a pas d'oeuvre dans votre panier</p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>