config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#homePage'
  get '/home' => 'pages#home'
  get '/who' => 'pages#who'
  get '/mentions' => 'pages#mentions'
  get '/conditions' => 'pages#conditions'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  
  resources :carts
  resources :cart_products
  
  resources :orders do 
    resources :payments, only: :new
  end
  resources :order_products

  resources :products do 
    resources :tags
  end

  resources :favorite_profils

  get "search", to: "products#search"
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick

  has_many :tags
  has_one_attached :photo
  belongs_to :user
  monetize :price_cents
  # has_many :cart_products, dependent: :nullify
  # has_many :order_products, dependent: :nullify
  has_many :cart_products
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_product
  validates :name, presence: true
  validates :category, presence: true
  validates :price_cents, presence: true

  # def self.search(search)
  #   where("category ILIKE ?", "%#{search}%")
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :update, :destroy]
  skip_before_action :authenticate_user!

  def index
    @products = policy_scope(current_user.products)
  end

  def search
    Product.reindex
    @products = Product.search(params[:q])
    authorize @products
  end

  def show
    authorize @product
  end
  
  def new
    @product = Product.new
    authorize @product
  end
  
  def create
    unless current_user
      flash[:alert] = "You must log in or sign in before creating product"
      redirect_to new_user_session_path
    else
      @product = Product.new(product_params)
      @product.user = current_user
      if @product.valid?
        @product.price = @product.price * 100
        @product.save!
        redirect_to product_path(@product)
      else
        render :new
      end
    end
    authorize @product
  end
  
  def edit
    authorize @product
  end
  
  def update
    @product.update(product_params)
    redirect_to product_path(@product)
    
    authorize @product
  end

  def destroy
    unless @product.user.id == current_user.id
      flash[:alert] = "You can't destroy this product"
      redirect_to products_path
    else
      @product.user = current_user
      @product.destroy
      flash[:notice] = "This product has been deleted"
      redirect_to products_path
    end
    authorize @product
  end
  
  private
  
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :category, :price_cents, :quantity, :tag, :photo, :description, :query)
  end

end

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="container back-height mt-4 mb-4">
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-7 mx-auto">
            <h2 class="text-center mb-4">Votre nouvelle oeuvre</h2>
            <div class="block-form">
                <%= simple_form_for @product do |f|%>
                    <%= f.input :name, label: 'Quel est le nom de votre produit ?', required: false %>
                    <%= f.input :price_cents, label: 'Quel est son prix ?', required: false %>
                    <%= f.input :category, as: :select, label: 'De quel catégorie votre produit fait-il partit ? (peinture, sculpture, etc..)', collection: { Peinture: "peinture", Sculpture: "sculpture", Vitrail: "vitrail"}, required: false %>
                    <%# f.input :tag, label: 'new_input_field_name' %>
                    <%= f.input :description, label: 'Donnez une description à votre oeuvre', required: false, input_html: { maxlength: 250, cols: 5, rows: 5 } %>
                    <%= f.input :photo, as: :file %>
                    <%= f.button :submit, "Valider mon produit", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container back-height mb-4 mt-4">
    <%= link_to "Ajouter", new_product_path(@product), class:"button-add"%>
    <div class="flex-section section">
        <h2 class="ml-3 d-flex align-items-center mb-0">Vos oeuvres</h2>
        <% if @products.count > 0 %>
            <h4 class="mr-3 mb-0">Vous avez <span class="gold"><%= @products.count %></span> oeuvres en vente</h4>
        <% else %>
            <h4 class="mb-0 mr-3">Vous avez <span class="gold"><%= @products.count %></span> oeuvre en vente</h4>
        <% end %>
    </div>
    <div class="row d-flex justify-content-around">
        <% if @products.count == 0 %>
            <p class="mt-3">Vous n'avez actuellement aucune oeuvre sur le site. Ajoutez en une en cliquant sur le bouton "Ajouter".</p>
        <% end %>
        
        <% count = 0 %>
        <% @products.each do |product|%>
            <% count += 1 %>
            <div class="col-sm-12 col-md-5 col-lg-4 d-flex justify-content-center">
                <div class="card card-product" style="width: 18rem;" data-number='<%= count %>' >
                    <% if product.photo.attachment.nil? %>
                        <%= link_to image_tag("https://cdn1.sklum.com/fr/774532/pack-de-2-chaises-en-velours-glamm.jpg"), product_path(product), class:"product-image border-radius" %>
                    <% else %>
                        <%= link_to product_path(product) do %>
                            <%= cl_image_tag product.photo.key, class: "product-image border-radius", crop: :fill %>
                        <% end %>
                    <% end %>
                    <div class="card-body">
                        <div>
                            <div class="d-flex justify-content-between">
                                <h5 class="card-title gold"><%= product.name.capitalize %></h5>
                                <p class="card-text price"><%= humanized_money(product.price) %> €</p>
                            </div>
                            <div class="mt-1 d-flex justify-content-between">
                                <h6 class="card-title category-title "><%= product.category.capitalize %></h6>
                                <%= link_to "+", edit_product_path(product), class:"", id:"" %>
                                <%= link_to "X", product_path(product), method: :delete, class:"", id:"" %>
                            </div>
                        </div>
                        <button class="button-heart btn-heart-index none" data-number="<%= count %>"><i id="" class="button-like far fa-heart"></i></button>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/products/new.html.erb
<div class="container back-height mt-4 mb-4">
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-7 mx-auto">
            <h2 class="text-center mb-4">Votre nouvelle oeuvre</h2>
            <div class="block-form">
                <%= simple_form_for @product do |f|%>
                    <%= f.input :name, label: 'Quel est le nom de votre produit ?', required: false %>
                    <%= f.input :price_cents, label: 'Quel est son prix ?', required: false %>
                    <%= f.input :category, as: :select, label: 'De quel catégorie votre produit fait-il partit ? (peinture, sculpture, etc..)', collection: { Peinture: "peinture", Sculpture: "sculpture", Vitrail: "vitrail"}, required: false %>
                    <%# f.input :tag, label: 'new_input_field_name' %>
                    <%= f.input :description, label: 'Donnez une description à votre oeuvre', required: false, input_html: { maxlength: 250, cols: 5, rows: 5 } %>
                    <%= f.input :photo, as: :file %>
                    <%= f.button :submit, "Valider mon produit", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/search.html.erb
<div class="container mb-5">
    <div class="title-flex-div section">
        <h2 class="align-item-title">Résultat de votre recherche :</h2>
        <% if @products.count <= 1 %>
            <h4 class="mr-3 "><span class="gold"><%= @products.count %></span> oeuvre</h4>
        <% else %>
            <h4 class="mr-3 "><span class="gold"><%= @products.count %></span> oeuvres</h4>
        <% end %>
    </div>
    <div class="row d-flex justify-content-around">
        <% count = 0 %>
        <% @products.each do |product|%>
            <% count += 1 %>
            <div class="col-sm-7 col-md-5 col-lg-4 d-flex justify-content-center">
                <div class="card card-product" style="width: 18rem;" data-number='<%= count %>'>
                    <% if product.photo.attachment.nil? %>
                        <%= link_to image_tag("https://cdn1.sklum.com/fr/774532/pack-de-2-chaises-en-velours-glamm.jpg"), product_path(product), class:"product-image" %>
                    <% else %>
                        <%= link_to product_path(product) do %>
                            <%= cl_image_tag product.photo.key, class: "product-image", crop: :fill %>
                        <% end %>
                    <% end %>
                    <div class="card-body">
                        <div>
                            <div class="d-flex justify-content-between">
                                <h5 class="card-title gold"><%= product.name.capitalize %></h5>
                                <% arr = [] %>
                                <% Order.all.each do |order| %>
                                    <% order.order_products.each do |order_product| %>
                                        <% arr << order_product.product_id %>
                                    <% end %>
                                <% end %>
                                
                                <% if arr.include?(product.id) %>
                                    <p class="card-text price opacity-grey"><%= humanized_money(product.price) %> €</p>
                                <% else %>
                                    <p class="card-text price"><%= humanized_money(product.price) %> €</p>
                                <% end %>
                            </div>
                            <h6 class="card-title mt-1">
                                <%= link_to product.category.capitalize, product_path(product), class:"button-product category-title"%>
                            </h6>
                        </div>
                        <button class="button-heart btn-heart-index none" data-number="<%= count %>"><i id='' class='button-like far fa-heart' ></i></button>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/products/show.html.erb
<body class="body-bg">
    <div class="container h-100">
        <!-- <%= link_to "All Products", products_path(@products), class:"button-add"%> -->
        <div class="row h-100 flex-product">
            <div class="col-xl-8 col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center height-back">
                <div class="width-700 margin-bottom-5">
                    <% if @product.photo.attachment.nil? %>
                        <img src="https://media.artsper.com/artwork/227887_1_grid@2x.jpg?MjIyOTI2NDkxNjAxMTE5MDEx" alt="" class="image-show-product center mt-5 mb-2">
                    <% else%>
                        <%= cl_image_tag @product.photo.key, class: "image-show-product center mt-5 mb-2", crop: :fill %>
                    <% end %>
                    <div class="ml-3 mr-3">
                        <div class= "section">
                            <h4 class="name-product"><%= @product.name.split(' ').each{ |x| x.capitalize! }.join(' ') %>, <span class="year"><%= @product.created_at.year %></span></h4>
                        </div>
                        
                        <div class="width-propos">
                            <div class="d-flex">
                                <h4 class="gold mr-3"><i class="fas fa-vector-square"></i></h4>
                                <h4 class="mb-3">À propos de cette oeuvre</h4>
                            </div>
                            <% if @product.description.nil? || @product.description == ""%>
                                <p>L'artiste n'a donné aucune description à cette oeuvre pour le moment.</p>
                            <% else %>
                                <p class="para-contact"><%= @product.description %></p>
                            <% end %>
                        </div>

                        <div class="width-propos mt-4 ">
                            <div class="d-flex align-items-center">
                                <div class="border-circle-info-product text-center gold">
                                    <p class="info-font-product gold m-0">!</p>
                                </div>
                                
                                <h4 class="mb-0 ml-2">Information importante</h4>
                            </div>
                            
                            <p class="para-contact mt-3 mb-2">Le moyen de paiement étant en phase de test, vous ne pourrez pas achetez cette oeuvre via notre plateforme, ni être livré par nos soins. <br>
                            Or vous avez la possibilité de contacter les artistes via notre rubrique <span><%= link_to 'à propos de nous', who_path, class:"gold link-contact-contrat para-contact m-0" %></span>.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12 back-product">
                <div class="info-product">
                    <div class="section-none w-100">
                        <% arr = [] %>
                        <% Order.all.each do |order| %>
                            <% order.order_products.each do |order_product| %>
                                <% arr << order_product.product_id %>
                            <% end %>
                        <% end %>
                        <% if arr.include?(@product.id) %>
                            <p class="info-price">PRIX</p>
                            <p class="price-show gold opacity-grey"><%= humanized_money(@product.price) %> €</p>
                        <% else %>
                            <p class="info-price">PRIX</p>
                            <p class="price-show gold"><%= humanized_money(@product.price) %> €</p>
                        <% end %>
                        <p class="livraison para-contact">Livraison & retour gratuits partout dans le monde</p>
                        <% if arr.include?(@product.id) %>
                            <button class="button-cart-vendu">VENDU </button>
                        <% else %>
                            <%= button_to 'Ajouter au panier', cart_products_path(product_id: @product), class:'button-cart button-add-in-show' %>
                        <% end %>
                        <div class="d-flex justify-content-around mt-3">
                            <button class="icone-info-share" id="button-heart-cart-circle"><i class="d-flex align-items-center justify-content-centers far fa-heart"></i></button>
                            <a href="mailto:alexis.flipo1@gmail.com allan.rouet@gmail.com" target=_blank ><i class="icone-info-price far fa-envelope"></i></a>

                        </div>
                    </div>
                    <div class="text-center section w-100 icone-none">
                        <p class="gold livraison-icon"><i class="fas fa-truck"></i></p>
                        <p class="livraison para-contact">Livraison sous 7 jours en moyenne</p>
                    </div>
                    <div class="pd-20 icone-none">
                        <div class="d-flex justify-content-between mb-2">
                            <p class="gold livraison-icon mr-5"><i class="fas fa-truck"></i></p>
                            <p class="para-contact">La livraison est assurée de bout en bout par LVG.</p>
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="gold livraison-icon mr-5"><i class="fas fa-box"></i></p>
                            <p class="para-contact">LVG applique le délai de rétractation de 14 jours, qui court à partir du jour de réception de l'oeuvre chez vous.</p>
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="gold livraison-icon mr-5"><i class="fas fa-lock"></i></p>
                            <p class="para-contact">Sur LVG, vous payez en toute sécurité par carte ou virement bancaires.</p>
                        </div>
                        <div class="d-flex justify-content-between mb-2">
                            <p class="gold livraison-icon mr-5"><i class="fas fa-check-circle"></i></p>
                            <p class="para-contact">LVG garantit sérieux et traçabilité.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <% arr = [] %>
    <% Order.all.each do |order| %>
        <% order.order_products.each do |order_product| %>
            <% arr << order_product.product_id %>
        <% end %>
    <% end %>

    <div class="contain black-back">
            <h4 class="other-product-artist mt-3">Autres suggestions</h4>
        <div class="row no-gutters">
            <% @product.user.products[0..3].each do |product| %>
                <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-6  d-flex justify-content-around">
                    <div class="other-product-div m-2">
                        <% if product.photo.attachment.nil? %>
                            <%= link_to image_tag("https://cdn1.sklum.com/fr/774532/pack-de-2-chaises-en-velours-glamm.jpg"), product_path(product), class:"product-image" %>
                            <p class="name-product-other"><%= product.name.capitalize %> - <%= humanized_money(product.price) %> €</p>
                        <% else %>
                            <%= link_to product_path(product), class:"border-none-product" do %>
                                <% unless arr.include?(product.id) %>
                                    <%= cl_image_tag product.photo.key, class: "product-image", crop: :fill %>
                                    <p class="name-product-other pt-2"><%= product.name.capitalize %> - <%= humanized_money(product.price) %> €</p>
                                <% else %>
                                    <%= cl_image_tag product.photo.key, class: "product-image", crop: :fill %>
                                    <p class="name-product-other pt-2"><%= product.name.capitalize %> - <span class="price-raye"><%= humanized_money(product.price) %> €</span></p>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</body>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>